import { currentTime } from "@/Functions/TS";

const time = currentTime();

export const questions = [
  {
    id: 1,
    keyword: [
      "hello",
      "hey",
      "wassup",
      "what's up",
      "salam",
      "Hello",
      "Hi",
      "Hey",
      "Good morning",
      "Good afternoon",
      "Good evening",
      "How are you?",
      "What's up?",
      "How's it going?",
      "How you doing?",
      "Howdy",
      "Hi there",
      "Hey there",
      "Yo",
      "Bonjour",
      "Hola",
      "Hola amigo/amiga",
      "Ciao",
      "Namaste",
      "Salaam",
      "Aloha",
      "Konnichiwa",
      "Annyeonghaseyo",
      "Sawasdee",
      "Hallo",
      "Guten Tag",
      "Guten Morgen",
      "Salut",
      "Shalom",
      "Merhaba",
      "Selamat pagi",
      "Szia",
      "Zdravstvuyte",
      "Ahoj",
      "Jambo",
      "Sawubona",
      "Marhaba",
      "Dia dhuit",
      "Sveiki",
      "Zdravo",
      "Ahojte",
      "Olá",
      "Merhaba",
    ],
    response: [
      "Hello! How can I assist you today?",
      `Good ${time}! How may I help you?`,
      "Hey there! It's great to see you. What can I do for you?",
      "Hi! What's on your mind?",
      "Hello! How's your day going so far?",
      "Hi! How are you doing today? Anything specific you'd like to discuss?",
      "Hello! What can I assist you with right now?",
      "Hello! I hope you're doing well. How can I be of service?",
      `Good ${time}! What brings you here at this hour?`,
      "Hi! What's been on your mind lately?",
      "Greetings! I'm here to help with any questions or tasks you have.",
      "Hello! I'm ready to assist you. What's your request?",
      `Good ${time}! How can I make your day better?`,
      "Hi there! How can I make your life a little easier today?",
      "Hello! What can I do to assist you today?",
      "Greetings! What can I do to brighten your day?",
      "Hi! I'm here to provide answers and support. What's on your agenda?",
      "Hello there! How can I be of service to you today?",
      "Good to see you! What can I help you with?",
      "Hi! Ready to assist with your questions and tasks. How can I assist?",
      "Hello! I'm at your service. What's on your mind?",
    ],

    option: ["Register for an Account", "Discover 9JAWISE"],
  },
  {
    id: 4,
    keyword: [
      "create account",
      "sign up",
      "register",
      "new account",
      "account setup",
      "account registration",
      "join",
      "get started",
      "enroll",
      "membership",
      "open account",
      "start using",
      "begin",
      "account initiation",
      "set up an account",
      "account application",
      "account enrollment",
      "account commencement",
      "account activation",
      "account establishment",
      "establish user profile",
      "start your journey",
      "membership creation",
      "initialize your account",
      "account commencement",
      "account onboarding",
      "user registration",
      "account initiation process",
      "begin using our services",
      "account sign-up",
      "account setup process",
      "user account creation",
      "membership sign-up",
      "account commencement process",
      "start your account journey",
      "account opening",
      "account initialization",
      "membership initiation",
      "begin using our platform",
    ],
    response: [
      `Sure, I can help you with account creation. Please visit our website at ${process.env.HOSTNAME} to create an account.`,
      `To create an account, you can visit our website at ${process.env.HOSTNAME} and follow the registration process.`,
      `Creating an account is easy. Just go to our website at ${process.env.HOSTNAME} and click on the 'Sign Up' or 'Register' button.`,
      `You can register for an account by visiting our website at ${process.env.HOSTNAME} and clicking on 'Get Started.'`,
      `New users can join our platform by going to ${process.env.HOSTNAME} and signing up for an account.`,
      `To get started, visit our website at ${process.env.HOSTNAME} and click on 'Register.' It only takes a few minutes to set up your account.`,
      `Enroll with us today! Go to ${process.env.HOSTNAME} to register and access our services.`,
      `Join our platform by visiting ${process.env.HOSTNAME} and creating a new account.`,
      `Ready to begin? Register for an account on our website at ${process.env.HOSTNAME} to get started.`,
      `Membership is just a few clicks away! Sign up at ${process.env.HOSTNAME} to create your account.`,
      `Opening an account is simple. Go to ${process.env.HOSTNAME} and click on 'Sign Up' to initiate the process.`,
      `To start using our services, visit ${process.env.HOSTNAME} and create an account.`,
      `Begin your journey with us! Go to ${process.env.HOSTNAME} and register for an account.`,
      `Get started by setting up your account on our website at ${process.env.HOSTNAME}.`,
      `You can start using our platform by applying for an account at ${process.env.HOSTNAME}.`,
      `Ready to activate your account? Visit ${process.env.HOSTNAME} to begin the registration process.`,
      `Establish your account with us by signing up at ${process.env.HOSTNAME}.`,
      `To initiate your account, go to ${process.env.HOSTNAME} and follow the account creation process.`,
      `Join our platform today by enrolling at ${process.env.HOSTNAME} and setting up your account.`,
      `Create an account and start using our services today! Visit ${process.env.HOSTNAME} to get started.`,
      `Ready to embark on this journey? Visit our website at ${process.env.HOSTNAME} and create your account.`,
      `We're excited to have you on board! Register for an account at ${process.env.HOSTNAME} to get started.`,
      `Begin your experience with us by signing up for an account at ${process.env.HOSTNAME}.`,
      `Your account is just a few clicks away. Join us at ${process.env.HOSTNAME} to get started.`,
      `Join our community by becoming a member. Sign up for an account at ${process.env.HOSTNAME} today.`,
      `Eager to explore our services? Start by creating an account at ${process.env.HOSTNAME}.`,
      `Welcome to our platform! Visit ${process.env.HOSTNAME} and complete the registration to access our features.`,
      `Your journey with us begins here. Register for an account at ${process.env.HOSTNAME} to unlock the possibilities.`,
      `New opportunities await! Sign up at ${process.env.HOSTNAME} and start your account today.`,
      `We're here to assist you. Begin your account setup by visiting ${process.env.HOSTNAME}.`,
    ],
    option: ["Password reset help?", "Mobile app available?"],
  },
  {
    id: 2,
    keyword: [
      "website information",
      "about 9jaWise",
      "why 9jaWise",
      "why us",
      "choose us",
      "site details",
      "creator",
      "website purpose",
      "security measures",
      "encryption",
      "data protection",
      "privacy",
      "online finance platform",
      "finance management",
      "financial services",
      "financial solutions",
      "information security",
      "financial platform",
      "site features",
      "site functionality",
      "testimonials",
      "user experiences",
      "about",
    ],
    response: [
      `Welcome to 9jaWise! It was created by SoolaimanG in 2023.`,
      `9jaWise is a comprehensive online finance management platform designed to assist individuals and businesses in managing their finances effectively.`,
      `Our website employs top-tier encryption algorithms to safeguard your financial data and ensure the utmost privacy and security.`,
      `We offer a range of financial services and solutions to address various financial challenges and help you make informed decisions.`,
      `At 9jaWise, your data privacy is of the utmost importance. We adhere to stringent privacy policies to protect your personal and financial information.`,
      `Our platform provides tools and resources for budgeting, expense tracking, investment analysis, and financial planning to help you achieve your financial goals.`,
      `Our dedicated support team is available 24/7 to assist you with any inquiries or issues you may have.`,
      `But don't just take our word for it. Here are some testimonials from our users:`,
      `"9jaWise has transformed the way I manage my finances. It's user-friendly and incredibly secure. I couldn't be happier!" - John Doe`,
      `"I've tried many financial apps, but 9jaWise stands out. The investment analysis has helped me make smarter investment decisions." - Jane Smith`,
      `"I love the budgeting features. It's helped me save more and stay on top of my financial goals." - David Johnson`,
      "Our mission at 9jaWise is to empower individuals and businesses to achieve financial success and security.",
      "We continuously update our platform to offer the latest financial tools and technologies to our users.",
      "Rest assured that your financial data is shielded from unauthorized access, thanks to our robust encryption and security protocols.",
      "Our commitment to user satisfaction is unwavering. We value your feedback and continually strive to improve our services.",
      "Explore our user-friendly dashboard, where you can gain insights into your finances at a glance.",
      "Manage your investments with confidence using our investment analysis tools, tailored to your financial goals.",
      "We believe that financial education is key. That's why we provide an extensive library of articles and resources to enhance your financial literacy.",
      "Join the growing community of 9jaWise users who have taken control of their finances and achieved their financial aspirations.",
      "Your financial well-being is our priority, and we're here to support you on your journey to financial success.",
      `To learn more about us or get started, visit our website at ${process.env.HOSTNAME}.`,
    ],
    option: ["More about 9jawise", "9ja features"],
  },
  {
    id: 3,
    keyword: [
      "features",
      "site capabilities",
      "what can it do",
      "functionality",
      "tools",
      "services",
      "financial management",
      "budgeting",
      "expense tracking",
      "investment analysis",
      "financial planning",
      "data security",
      "privacy measures",
      "customer support",
      "user-friendly",
      "resource library",
      "financial literacy",
      "community",
      "user testimonials",
      "financial success",
    ],
    response: [
      "9jaWise offers a comprehensive suite of features to help you take control of your finances and achieve financial success.",
      "Key features of our platform include expense tracking, budgeting tools, investment analysis, and financial planning resources.",
      "Easily monitor and categorize your expenses to gain insights into your spending habits.",
      "Create and manage budgets to achieve your financial goals.",
      "Get comprehensive investment analysis and recommendations to maximize your returns.",
      "Plan for your future with retirement and financial goal planning tools.",
      "Your financial data is protected with state-of-the-art encryption and privacy measures.",
      "Our dedicated customer support team is available 24/7 to assist you with any inquiries or issues you may have.",
      "Our user-friendly dashboard provides a seamless and intuitive user experience.",
      "Access a wealth of resources and educational content to enhance your financial literacy.",
      "Join a vibrant community of users who have achieved financial success with 9jaWise.",
      "Don't just take our word for it. Read testimonials from our satisfied users.",
      "We're here to support you on your journey to financial wellness.",
      `To explore all these features and more, visit our website at ${process.env.HOSTNAME}.`,
    ],
    option: ["More features", "Process"],
  },
  {
    id: 5,
    keyword: [
      "how it works",
      "platform operation",
      "process",
      "financial management process",
      "getting started",
      "account creation",
      "using 9jaWise",
      "financial tracking",
      "investment analysis",
      "budgeting",
      "user experience",
      "privacy measures",
      "customer support",
      "user community",
      "resources",
      "financial insights",
      "dashboard features",
      "financial goals",
      "investment recommendations",
      "data privacy",
      "user support",
      "community engagement",
      "educational resources",
      "create an account",
      "open an account",
      "create a new account",
      "create account",
    ],
    response: [
      "Getting started with 9jaWise is easy. Here's how it works:",
      `Account Creation: Begin by creating an account on our website. You can do this by visiting ${process.env.HOSTNAME} and following the registration process.`,
      " Dashboard: Once you're logged in, you'll be greeted by our user-friendly dashboard. This is your central hub for managing your finances.",
      " Financial Tracking: Use our tools to track your expenses and gain insights into your spending habits. Categorize your expenses to stay organized.",
      " Budgeting: Create and manage budgets to set financial goals and track your progress.",
      " Investment Analysis: Access our investment analysis tools to make informed investment decisions and maximize your returns.",
      " Financial Planning: Plan for your future with retirement and financial goal planning resources.",
      " Data Security: Rest assured that your financial data is protected with the highest level of encryption and privacy measures.",
      " Customer Support: Our dedicated support team is available 24/7 to assist you with any questions or issues you may encounter.",
      " User Community: Join our user community, where you can connect with others who have achieved financial success with 9jaWise.",
      " Resources: Explore our extensive library of articles and educational content to enhance your financial literacy.",
      "With 9jaWise, you can take control of your finances and work towards financial wellness with confidence.",
      `Ready to get started? Visit our website at ${process.env.HOSTNAME} to create your account and begin your financial journey.`,
      " Financial Insights: Gain valuable financial insights through our analytics tools, helping you make data-driven decisions.",
      " Dashboard Features: Explore the various features on your dashboard, such as transaction history, savings goals, and investment summaries.",
      " Financial Goals: Set and monitor your financial goals, whether it's saving for a vacation or planning for retirement.",
      " Investment Recommendations: Receive personalized investment recommendations based on your financial profile and goals.",
      " Data Privacy: Your data is our top priority. We employ robust privacy measures to ensure your information remains confidential.",
      " User Support: Our responsive customer support team is here to assist you with any inquiries or issues, ensuring a smooth user experience.",
      "Community Engagement: Connect with fellow users, share experiences, and learn from one another within our active user community.",
      "Educational Resources: Enhance your financial literacy with our extensive library of articles, videos, and interactive resources.",
      "At 9jaWise, we've designed our platform to be a one-stop solution for your financial management needs, empowering you to achieve your financial aspirations.",
      "Ready to embark on your financial journey? Start today by visiting our website at ${process.env.HOSTNAME} to create your account.",
    ],
    option: ["why 9jawise"],
  },
  {
    id: 6,
    keyword: [
      "end conversation",
      "done chatting",
      "finished",
      "goodbye",
      "exit",
      "terminate",
      "close chat",
    ],
    response: [
      "Thank you for using 9jaWise! If you have any more questions in the future, feel free to return. Have a great day!",
      "You're welcome! If you ever need assistance again, don't hesitate to reach out. Goodbye!",
      "Great chatting with you! If you think of anything else later, just visit our website. Goodbye for now!",
      "If you have any more inquiries in the future, please don't hesitate to contact us. Have a wonderful day!",
      "Goodbye for now! Remember, we're here to help whenever you need financial guidance. Take care!",
    ],
    option: ["open an account"],
  },
  {
    id: 7,
    keyword: [
      "end conversation",
      "done chatting",
      "finished",
      "goodbye",
      "exit",
      "terminate",
      "close chat",
      "Ok",
      "Thank you",
      "you are the best",
      "am done",
      "nice",
      "good",
      "Wrap it up",
      "Conclude discussion",
      "Farewell",
      "Signing off",
      "Chat finished",
      "All done",
      "End session",
      "That's it",
      "Finished chatting",
      "Stop",
      "Cease conversation",
      "Exit chat",
      "Close this",
      "Chat over",
      "I'm out",
      "Chat complete",
      "Conversation done",
      "Done here",
      "See you later",
      "I'm finished",
      "That's all for now",
      "It's been great chatting",
      "Goodbye for now",
      "All set",
      "Conversation complete",
      "Closing the chat",
      "Done for the day",
      "Conclude this",
      "Let's wrap it up",
    ],
    response: [
      "Thank you for using 9jaWise! If you have any more questions in the future, feel free to return. Have a great day!",
      "You're welcome! If you ever need assistance again, don't hesitate to reach out. Goodbye!",
      "Great chatting with you! If you think of anything else later, just visit our website. Goodbye for now!",
      "If you have any more inquiries in the future, please don't hesitate to contact us. Have a wonderful day!",
      "Goodbye for now! Remember, we're here to help whenever you need financial guidance. Take care!",
      "If you ever want to resume this conversation or need assistance in the future, simply visit our website and start a new chat. Goodbye!",
      "Your satisfaction is important to us. If you have more questions later, we're just a message away. Take care!",
      "Thanks for chatting with us! Remember, you can return anytime if you need further assistance. Goodbye for now!",
      "Goodbye and have a fantastic day ahead! Don't hesitate to return if you have more inquiries or need support.",
      "If you ever need help with your finances again, don't hesitate to reach out. Goodbye, and best wishes!",
    ],
    option: ["about our creator"],
  },
  {
    id: 50,
    keyword: [
      "Mobile app",
      "App download",
      "iOS app",
      "Android app",
      "Mobile application",
      "Download app",
      "App installation",
      "App availability",
      "Smartphone app",
      "Mobile platform",
      "Get the app",
      "App compatibility",
      "Mobile device",
      "App for iOS",
      "App for Android",
      "Install on mobile",
      "Access on the go",
      "Mobile access",
      "Smartphone access",
      "Mobile app features",
      "App functionality",
      "Mobile app benefits",
      "App for my phone",
      "Mobile app support",
      "Mobile app assistance",
      "Access on mobile device",
      "Mobile app options",
      "Mobile app versions",
      "Mobile app compatibility",
      "App for my smartphone",
    ],
    response: [
      "I'm sorry, our mobile app is still in development and is not available for download yet.",
      "Currently, we do not have a mobile app, but you can access our services through our website.",
      "Our mobile app is in the works, but it's not available for download at the moment.",
      "We're working on a mobile app, but it's not ready for download yet.",
      "At this time, we don't have a mobile app, but you can access our services via our website.",
      "Unfortunately, our mobile app is not available at the moment.",
      "Our mobile app is still under development and not available for download.",
      "We're working hard to create a mobile app, but it's not ready for use yet.",
      "I apologize, but our mobile app is not yet released.",
      "The mobile app is in development and will be available in the future, but not now.",
      "Currently, we don't have a mobile app, but you can access our platform through our website.",
      "I regret to inform you that our mobile app is not available at this time.",
      "Our team is actively developing a mobile app, but it's not downloadable yet.",
      "The mobile app is in progress but not ready for users just yet.",
      "We're excited to announce that a mobile app is in the works, but it's not available for download.",
      "I'm sorry, but our mobile app is not yet launched.",
      "Currently, we don't offer a mobile app, but you can use our website to access our services.",
      "Our mobile app is currently in development, and we'll let you know when it's ready for download.",
      "I apologize for any inconvenience, but our mobile app is not available right now.",
      "Our team is working on a mobile app, but it's not released yet.",
    ],
    option: ["Invite friends to join?", "Access transaction history?"],
  },
  {
    id: 57,
    keyword: [
      "Password reset",
      "Forgot password",
      "Reset my password",
      "Change password",
      "Account security",
      "Can't log in",
      "Password recovery",
      "Account access",
      "Forgot my credentials",
      "Unlock my account",
      "Can't remember password",
      "Reset login details",
      "Account authentication",
      "Recover access",
      "Change my login",
      "Help with password",
      "Account recovery",
      "Lost password",
      "Reset my credentials",
      "Trouble logging in",
    ],
    response: [
      "If you need to reset your password, simply navigate to the sign-in page. There, you'll find the 'Forgot Password' option, which will guide you through the password reset process.",
      "To reset your password, go to the sign-in page and click on the 'Forgot Password' link. Follow the instructions to reset your password and regain access to your account.",
      "If you've forgotten your password, don't worry. Head to the sign-in page and look for the 'Forgot Password' option. You can reset your password there and get back into your account.",
      "You can reset your password by visiting the sign-in page. Look for the 'Forgot Password' link, follow the steps, and you'll have your new password in no time.",
      "Lost your password? No problem! Go to the sign-in page and click on 'Forgot Password.' Follow the instructions, and you'll be able to reset your password and access your account.",
      "To reset your password, please navigate to the sign-in page. There, you'll find the 'Forgot Password' option that will guide you through the process of resetting your password.",
      "Don't worry if you've forgotten your password. Simply visit the sign-in page and click on 'Forgot Password.' Follow the steps to reset your password and regain access to your account.",
      "If you're having trouble with your password, you can easily reset it. Just go to the sign-in page and click on 'Forgot Password.' Follow the prompts to reset your password and secure your account.",
      "Lost your credentials? No worries! Head over to the sign-in page, where you'll see the 'Forgot Password' option. Click on it to reset your password and regain access to your account.",
      "Experiencing login troubles? No problem. Navigate to the sign-in page, and you'll find the 'Forgot Password' link. Click on it to reset your password and regain access to your account.",
    ],
    option: ["I'm locked out of my account. What do I do?"],
  },
  {
    id: 59,
    keyword: [
      "Locked out of account",
      "Can't access my account",
      "Account access issue",
      "Account lockout",
      "I can't log in",
      "Can't sign in",
      "Forgot my login details",
      "Account security problem",
      "Lost my password",
      "Account authentication trouble",
      "Account recovery",
      "Trouble with login",
      "Access denied",
      "Help with account access",
      "Can't get into my account",
      "Login issues",
      "Account blocked",
      "Account is locked",
      "Account is inaccessible",
      "Can't get to my account",
    ],
    response: [
      "If you're locked out of your account, don't worry! You can contact our customer service for assistance. Simply type 'modes' and select 'Customer Service' to get help with regaining access to your account.",
      "Account locked? No problem. Reach out to our customer service by typing 'modes' and selecting 'Customer Service.' They'll assist you in resolving the issue.",
      "Don't fret if you're locked out of your account. Type 'modes' and select 'Customer Service' to contact our support team for help with account access.",
      "Locked out of your account? Contact our customer service for assistance by typing 'modes' and selecting 'Customer Service.' They're here to help you get back in.",
      "Having trouble accessing your account? No worries! Type 'modes' and select 'Customer Service' to get in touch with our support team for account recovery.",
      "Account lockout can be frustrating, but we're here to help. Type 'modes' and select 'Customer Service' to reach out for assistance with your locked account.",
      "If you're unable to access your account, don't panic. Type 'modes' and select 'Customer Service' to contact our support team for account recovery.",
      "Account issues? Reach out to our customer service for assistance. Just type 'modes' and select 'Customer Service' to get help with your locked account.",
      "Locked out of your account and need help? No problem! Type 'modes' and select 'Customer Service' to contact our support team for assistance.",
      "Account locked? Reach out to our customer service by typing 'modes' and selecting 'Customer Service' to get the help you need for account recovery.",
      "Having trouble logging in? Type 'modes' and select 'Customer Service' to contact our support team for assistance with your locked account.",
      "Account access problems? Type 'modes' and select 'Customer Service' to reach out to our support team for help with account recovery.",
      "Don't let a locked account keep you out. Type 'modes' and select 'Customer Service' to contact our support team for account recovery assistance.",
      "If you can't log in, we're here to help. Type 'modes' and select 'Customer Service' to reach out for assistance with your locked account.",
      "Account blocked? No worries. Type 'modes' and select 'Customer Service' to get in touch with our support team for account recovery.",
      "Locked out of your account and need help? Type 'modes' and select 'Customer Service' to contact our support team for assistance with your account access.",
      "Account issues? Reach out to our customer service for assistance. Type 'modes' and select 'Customer Service' to get the help you need for account recovery.",
      "Locked out of your account? Reach out to our customer service by typing 'modes' and selecting 'Customer Service' to get help with account recovery.",
      "Account access problems? Type 'modes' and select 'Customer Service' to contact our support team for assistance with your locked account.",
      "Don't let a locked account keep you out. Type 'modes' and select 'Customer Service' to contact our support team for account recovery assistance.",
    ],
    option: ["I'm locked out of my account. What do I do?"],
  },
  {
    id: 9,
    keyword: [
      "about our creator",
      "who created this",
      "website creator",
      "who is behind this",
      "developer",
      "who developed this",
      "creator of 9jaWise",
      "built this website",
      "developer information",
      "know the creator",
      "tell me about the developer",
      "developer details",
      "who made this",
      "developer info",
      "designer of 9jaWise",
      "team behind this",
      "developer of this website",
      "know the developer",
      "creator's name",
      "developer's name",
    ],
    response: [
      "Thank you for asking you can reach the developer of this @soolaimangee@gmail.com",
      "The creator of this beauty is SoolaimanGee",
      "I was created by SoolaimanGee",
      "Here is the creators phone number #07068214943",
      "Soolaiman G. Abubakar",
    ],
    option: ["about our creator"],
  },
  {
    id: 10,
    keyword: [
      "I'm fine.",
      "Doing well.",
      "I'm good.",
      "Everything's okay.",
      "All is well.",
      "I'm great.",
      "No issues.",
      "Feeling good.",
      "Life is good.",
      "Doing fine, thanks.",
      "No complaints.",
      "I'm okay.",
      "Pretty good.",
      "Not bad.",
      "Feeling great.",
      "I'm fantastic.",
      "In good spirits.",
      "Healthy and happy.",
      "Can't complain.",
      "Things are fine.",
      "Absolutely fine.",
      "Doing awesome.",
      "Couldn't be better.",
      "Top-notch.",
      "In a good place.",
      "Pretty well.",
      "Thriving.",
      "Well and happy.",
      "Healthy and content.",
      "All good here.",
      "In high spirits.",
      "Fantastic as ever.",
      "Smooth sailing.",
      "Living the dream.",
      "Couldn't be happier.",
      "Feeling on top of the world.",
      "In excellent shape.",
      "Having a great day.",
      "In a fantastic mood.",
      "Full of positivity.",
    ],
    response: [
      "That's great to hear! How can I assist you today?",
      "I'm glad to hear that you're doing well! Is there anything specific you'd like to know or discuss?",
      "Awesome! If you have any questions or need assistance with anything, feel free to ask.",
      "Fantastic! If there's anything you'd like to talk about or inquire about, please let me know.",
      "It's wonderful to know that you're doing well! How can I be of service today?",
      "Good to hear! If you ever have any questions or need information, don't hesitate to ask.",
      "Great to hear you're in good spirits! How can I assist you today?",
      "That's fantastic news! If there's anything you'd like to discuss or learn more about, feel free to ask.",
      "Excellent! If you ever need assistance or have inquiries, just let me know.",
      "I'm happy to hear that! Is there anything specific you'd like to chat about?",
      "Awesome! If you have any questions or need assistance with something, please feel free to ask.",
      "That's wonderful to hear! How can I help you today?",
      "I'm delighted that you're doing well! If you have any questions or need information, don't hesitate to reach out.",
      "Fantastic news! Is there anything specific you'd like to know or discuss?",
      "I'm here to assist you, so if there's anything on your mind, feel free to share or inquire.",
      "That's great! If there's anything you'd like to talk about or any questions you have, please let me know.",
      "Good to know you're in a positive mood! How can I be of service today?",
      "I'm glad to hear that! If you ever need assistance or have questions, don't hesitate to ask.",
      "That's fantastic! If you have any inquiries or topics you'd like to explore, feel free to mention them.",
      "Excellent! If there's anything specific you'd like to discuss or learn more about, feel free to ask.",
      "I'm here to assist you with anything you need, so please don't hesitate to ask.",
    ],
    option: ["9jaWise for business owners"],
  },
  {
    id: 11,
    keyword: [
      "Fintech for business owners",
      "Financial tools for businesses",
      "Business finance software",
      "Small business financial services",
      "Entrepreneur finance app",
      "Business banking solutions",
      "Fintech solutions for startups",
      "Business expense management",
      "Online accounting for businesses",
      "Cash flow management for entrepreneurs",
      "Payment processing for businesses",
      "Business loan applications",
      "Invoice and billing software for business",
      "Tax management for small businesses",
      "Financial planning for startups",
      "Business financial analytics",
      "Credit and financing options for entrepreneurs",
      "Business budgeting tools",
      "Investment options for business owners",
      "Financial advisory services for startups",
      "Online banking for businesses",
      "Business savings and investments",
      "Expense tracking for entrepreneurs",
      "Business payroll solutions",
      "Digital financial services for startups",
    ],
    response: [
      "9jaWise offers a comprehensive suite of financial tools designed to streamline your business operations and enhance your financial management. With 9jaWise, you can manage expenses, track cash flow, process payments, and more.",
      "With 9jaWise for business owners, you'll have access to advanced financial solutions that can help you optimize your finances, from accounting and invoicing to investment options and financial analytics.",
      "9jaWise's fintech web app is tailored to meet the specific needs of business owners. You can efficiently manage your finances, handle payroll, analyze financial data, and make informed decisions for your business's growth.",
      "We provide fintech solutions through 9jaWise that empower entrepreneurs and small business owners. Our platform offers features such as online banking, expense tracking, and tax management to simplify financial management.",
      "Business owners can benefit from 9jaWise's fintech services, including payment processing, invoice management, and access to various financial products and services. Our goal is to make financial management easier for you with 9jaWise.",
      "9jaWise's fintech platform is designed to help startups and business owners succeed. You can explore investment opportunities, access financial advice, and stay on top of your business's financial health with 9jaWise.",
      "Discover the advantages of 9jaWise's fintech web app for business owners, including access to financial experts, tools for budgeting and forecasting, and solutions for improving your business's financial efficiency.",
      "We offer a comprehensive suite of fintech services for entrepreneurs and business owners through 9jaWise. From managing cash flow to optimizing tax strategies, our platform is designed to help your business thrive with 9jaWise.",
      "With 9jaWise's fintech solutions, you can focus on growing your business while we take care of the financial aspects. Enjoy features like online banking, expense tracking, and financial planning with 9jaWise.",
      "9jaWise's fintech platform is your partner in financial success. We provide a range of services, including expense management, payment solutions, and investment options, all tailored to meet the needs of business owners.",
    ],
    option: ["Delete account"],
  },
  {
    id: 12,
    keyword: [
      "Delete my account",
      "Close my account",
      "Cancel my account",
      "Remove my account",
      "Terminate my account",
      "Deactivate my account",
      "Account deletion",
      "Account closure",
      "Account cancellation",
      "Account removal",
      "Account termination",
      "Account deactivation",
      "How to delete my account",
      "Erase my account",
      "Wipe my account",
      "End my account",
      "Shut down my account",
      "Close my profile",
      "Cancel my membership",
      "Account removal request",
    ],
    response: [
      "I see that you're thinking about deleting your account. It's important to remember that this action is irreversible and will result in the loss of all your account data. Please review your decision carefully. If you have any questions or need assistance, feel free to ask.",
      "Account deletion is a significant step, and I want to ensure you're making an informed choice. Deleting your account means all your information will be permanently erased. If you have any doubts or need help, don't hesitate to reach out.",
      "Before proceeding with account deletion, please be aware that this action is final. Your account data will be permanently removed. If you have concerns or would like assistance with any account-related issues, please let me know.",
      "I understand you're considering account deletion. It's crucial to weigh the consequences carefully. Deleting your account means losing access to your data. If you have any uncertainties or require support, I'm here to assist you.",
      "Account deletion is a permanent decision. Take a moment to think about it. If you have any unresolved issues or concerns related to your account, I'm here to help you resolve them.",
      "Deleting your account is a significant step. Please ensure it's what you truly want, as all your account data will be erased permanently. If you have any questions or need assistance, don't hesitate to ask for help.",
      "I want to make sure you're aware that account deletion is irreversible. If you have any hesitations or questions, please reach out. I'm here to assist you with any account-related matters.",
      "Before proceeding with account deletion, consider the impact on your data and access. If you're uncertain or need assistance with any account issues, feel free to discuss them with me.",
      "Deleting your account will result in the permanent loss of all your account data. Please take the time to think about it. If you have any account-related concerns or need assistance, I'm here to support you.",
      "Account deletion is a big decision. Make sure it aligns with your intentions, as it will erase all your account information. If you have any doubts or require assistance, please don't hesitate to ask for help.",
    ],
    option: ["Talk to reprentative", "Is this website fast"],
  },
  {
    id: 13,
    keyword: [
      "Talk to a representative",
      "Speak to a live agent",
      "Contact customer support",
      "Connect with an agent",
      "Get in touch with support",
      "Request assistance from a person",
      "Live chat with a representative",
      "Customer service help",
      "Agent support",
      "Need a human",
      "Human assistance",
      "Talk to a real person",
      "Agent chat",
      "Customer service representative",
      "Agent assistance",
      "Support agent",
      "Customer help",
      "Speak with a support team member",
      "Get help from a person",
      "Agent communication",
      "Request agent assistance",
      "Contact support team",
      "Live agent chat",
      "Agent help needed",
      "Human customer support",
      "Agent conversation",
      "Assistance from an agent",
      "Reach out to an agent",
      "Talk to an operator",
      "Live assistance",
      "Agent inquiry",
      "Customer support contact",
      "Need support from a person",
      "Agent availability",
      "Agent request",
      "Agent contact",
      "Get assistance from a representative",
      "Agent interaction",
      "Contact live customer support",
      "Speak with a human agent",
    ],
    response: [
      "Please reach out to a representative via this email @soolaimangee@gmail.com",
    ],
    option: ["About security", "Developer"],
  },
  {
    id: 14,
    keyword: [
      "Website security",
      "Is this site secure?",
      "Security measures",
      "Protect my data",
      "Secure browsing",
      "Data privacy",
      "SSL certificate",
      "Encryption",
      "Safe website",
      "Security features",
      "Online safety",
      "Cybersecurity",
      "Data protection",
      "Secure transactions",
      "Website privacy",
      "Secure login",
      "Security protocols",
      "HTTPS",
      "Protect my information",
      "Web security measures",
      "Online security",
      "Site safety",
      "Secure account",
      "Security standards",
      "Website firewall",
      "Web safety",
      "Security precautions",
      "Website data security",
      "Privacy assurance",
      "Website protection",
      "Web encryption",
      "Secure online experience",
      "Information security",
      "Safe online transactions",
      "Site authentication",
      "Web vulnerability",
      "Data encryption",
      "Secure website practices",
      "User data security",
      "Website trustworthiness",
      "Security assurance",
      "Website safety measures",
      "Secured web browsing",
      "Protecting user information",
      "Website authentication",
    ],
    response: [
      "At 9ja Wise, we take website security very seriously. We employ state-of-the-art security measures to protect your data and ensure a safe browsing experience.",
      "Your security is our top priority at 9ja Wise. We use encryption technology and rigorous security protocols to safeguard your information.",
      "Rest assured, 9ja Wise is committed to providing a secure online environment. We continuously monitor for potential threats and vulnerabilities.",
      "9ja Wise is equipped with advanced security features, including SSL encryption, to keep your data safe while browsing our website.",
      "We understand the importance of data privacy. 9ja Wise adheres to strict privacy policies and industry security standards to protect your information.",
      "When it comes to security, you can trust 9ja Wise. Our website is designed with your safety in mind, ensuring a secure online experience.",
      "Your trust and security matter to us. 9ja Wise employs robust security practices to safeguard your personal and financial information.",
      "We go the extra mile to ensure the security of 9ja Wise. Our team is dedicated to maintaining a secure online environment for all users.",
      "At 9ja Wise, we use industry-leading encryption techniques to secure your data and maintain the confidentiality of your information.",
      "You can have peace of mind using 9ja Wise. Our website is protected by stringent security measures to keep your information safe.",
      "Security is non-negotiable at 9ja Wise. We invest in the latest security technologies to provide you with a safe and protected web experience.",
      "We are committed to transparency when it comes to security. 9ja Wise follows best practices to ensure the safety of your data.",
      "Your data's security is paramount at 9ja Wise. We use encryption to protect your information during transmission and storage.",
      "Rest assured, 9ja Wise is designed with your online safety in mind. Our security infrastructure is constantly updated to combat emerging threats.",
      "9ja Wise is your secure online destination. We take every precaution to protect your information and maintain the integrity of our platform.",
      "We understand the importance of trust and security. 9ja Wise implements strict access controls and data encryption to safeguard your data.",
      "Security is not just a feature; it's a commitment at 9ja Wise. We work tirelessly to ensure your online safety and privacy.",
      "You can count on 9ja Wise for a secure online experience. Our security measures are designed to protect you and your data.",
      "At 9ja Wise, we are dedicated to your security. Our website undergoes regular security audits to identify and mitigate risks.",
      "Your security matters to us at 9ja Wise. We take proactive steps to protect your data and maintain the trust you place in our platform.",
    ],
    option: ["How fast is this website", "How to send money"],
  },
  {
    id: 15,
    keyword: [
      "Transaction speed",
      "Real-time transactions",
      "How fast are transactions?",
      "Instant transactions",
      "Transaction processing time",
      "Speed of payments",
      "Quick transactions",
      "Real-time payment processing",
      "Transaction time",
      "Swift transactions",
      "Fast payment processing",
      "Real-time money transfer",
      "Transaction speed inquiry",
      "Payment processing speed",
      "Speed of money transfer",
      "Real-time transaction updates",
      "Fast money transfer",
      "Real-time transaction status",
      "Transfer speed",
      "Rapid transactions",
      "Real-time payment updates",
      "Transaction processing speed",
      "Payment speed",
      "Quick payment processing",
      "Real-time transaction tracking",
      "Speedy money transfer",
      "Instant payment processing",
      "Real-time transaction notifications",
      "Transaction processing rate",
      "Quick money transfer",
      "Real-time transaction inquiry",
      "Payment processing time",
      "Fast transaction completion",
      "Real-time payment status",
      "Real-time transaction confirmation",
      "Transaction speed details",
      "Payment processing efficiency",
      "Real-time payment verification",
      "Speedy transaction updates",
      "Quick transaction processing",
      "Real-time money transfer status",
    ],
    response: [
      "At 9ja Wise, we pride ourselves on the speed and real-time nature of our transactions. Our platform is designed for swift and seamless money transfers.",
      "You can expect instant transactions on 9ja Wise. We prioritize real-time payment processing for your convenience.",
      "Our transaction processing is lightning fast. You'll experience quick and efficient payments when using 9ja Wise.",
      "At 9ja Wise, we offer real-time money transfers, ensuring that your transactions are processed without delay.",
      "Transaction speed is a top priority at 9ja Wise. We strive to provide you with the fastest payment processing in real-time.",
      "With 9ja Wise, you'll enjoy the benefit of instant transactions. Our platform is designed for swift and efficient payment processing.",
      "Our payment processing is designed to be rapid, allowing you to experience the convenience of real-time transactions.",
      "At 9ja Wise, we ensure that your transactions happen in real-time, providing you with quick and seamless payment experiences.",
      "Transaction speed matters to us. You can trust 9ja Wise for real-time money transfers and efficient payment processing.",
      "We've optimized our platform for fast payment processing. Expect real-time transactions when using 9ja Wise.",
      "Swift transactions are a hallmark of 9ja Wise. We prioritize real-time payment processing to meet your needs.",
      "At 9ja Wise, we're committed to providing you with fast and real-time money transfers. Your transactions are our priority.",
      "With 9ja Wise, you'll experience the convenience of instant transactions. Our platform ensures real-time payment processing.",
      "Transaction speed is crucial, and we excel at it. Expect quick and efficient payments with 9ja Wise.",
      "Real-time money transfer is a standard at 9ja Wise. We're dedicated to providing you with speedy transaction processing.",
      "At 9ja Wise, we offer real-time payment updates, allowing you to track your transactions as they happen.",
      "You can trust 9ja Wise for real-time transaction status. Our platform keeps you informed every step of the way.",
      "Our platform offers fast transaction processing and real-time payment updates, ensuring a seamless experience.",
      "With 9ja Wise, you'll receive real-time transaction notifications, keeping you in the know at all times.",
      "At 9ja Wise, we prioritize transaction processing speed. Expect quick and real-time payment confirmation.",
    ],
    option: [""],
  },
  {
    id: 16,
    keyword: [
      "Send money",
      "How to send money",
      "Money transfer",
      "Transfer funds",
      "Remittance",
      "Sending cash",
      "Money sending process",
      "How can I send money?",
      "Send money online",
      "Money transfer methods",
      "Transfer money",
      "Send funds",
      "Money sending options",
      "Transfer cash",
      "Sending funds",
      "Money transfer steps",
      "Send money abroad",
      "International money transfer",
      "Money transfer services",
      "Send money to a friend",
      "Online money transfer",
      "Money transfer instructions",
      "Sending money to family",
      "Money transfer guide",
      "Send money to another country",
      "How do I transfer money?",
      "Money transfer process",
      "Sending money to someone",
      "Wire money",
      "Electronic funds transfer",
      "Sending money overseas",
      "Money sending guide",
      "How to send money to family",
      "Transfer money online",
      "Money remittance steps",
      "Sending money to a bank account",
      "Money transfer options",
      "Wire transfer process",
      "Sending money to a loved one",
      "Digital money transfer",
    ],
    response: [
      "Sending money is easy with our platform. You can initiate a transfer online or through our mobile app.",
      "To send money, log in to your account and select the 'Send Money' option. Follow the on-screen instructions to complete the transfer.",
      "You can transfer funds to friends and family by entering their contact details and the amount you wish to send.",
      "Our money transfer service offers a secure and convenient way to send funds to anyone, anywhere in the world.",
      "Sending money is just a few clicks away. Use our platform to transfer funds quickly and securely.",
      "We provide multiple money transfer methods, including bank transfers, online payments, and more. Choose the one that suits you best.",
      "To send money online, navigate to the 'Transfer Funds' section and follow the prompts. It's a hassle-free process.",
      "Sending money to another country? We offer international money transfer services with competitive rates.",
      "You can trust our platform for safe and reliable money transfers. Your financial security is our priority.",
      "Our step-by-step money transfer guide will walk you through the process, making it easy to send funds to your desired recipient.",
      "We offer various options for sending money, whether it's to a friend, family member, or a bank account. It's all within your reach.",
      "Need to send money to a loved one? Our platform makes it simple and convenient to provide support when it matters most.",
      "With our digital money transfer service, you can send funds securely from the comfort of your home.",
      "Transfer money online with ease. We've streamlined the process to ensure a smooth and efficient experience.",
      "To send money to a bank account, enter the recipient's account details and the amount you'd like to transfer. It's that straightforward.",
      "Sending money overseas? Our international money transfer service offers competitive exchange rates and low fees.",
      "You can initiate a wire transfer through our platform. It's a reliable way to send money quickly and securely.",
      "Our electronic funds transfer service ensures that your money reaches its destination promptly and safely.",
      "Sending money to family or friends abroad? We offer a range of options to suit your needs, including online and mobile transfers.",
      "We understand the importance of sending money to loved ones. Our platform is designed with your convenience in mind.",
    ],
    option: ["About 9jaWise", "Security"],
  },
  {
    id: 17,
    keyword: [
      "What's your name?",
      "Your name?",
      "Who are you?",
      "Bot name",
      "Chatbot's name",
      "Your identity",
      "Introduce yourself",
      "Tell me your name",
      "What can I call you?",
      "Bot identity",
      "Identity",
      "Identification",
      "Who am I talking to?",
      "Are you a person?",
      "Your moniker",
      "Appellation",
      "What should I call you?",
      "Your title",
      "Appellative",
      "Naming",
      "Bot designation",
      "How do you refer to yourself?",
      "Your label",
      "Your handle",
      "What should I call you?",
      "Your preferred name",
      "Your chatbot title",
      "Tell me your designation",
      "Your chatbot handle",
      "How do you identify?",
      "What can I name you?",
      "Your chatbot moniker",
      "Chatbot label",
      "Identification name",
      "Your title as a chatbot",
      "Your chatbot identity",
      "Appellation of the chatbot",
      "How do you introduce yourself?",
      "How should I address you?",
      "Chatbot's self-identity",
      "Preferred chatbot name",
      "How are you known?",
      "Chatbot's calling",
      "Your chatbot name preference",
    ],
    response: [
      "I go by the name Bague.",
      "You can call me Bague, your helpful assistant.",
      "I'm known as Bague, here to assist you.",
      "My name is Bague, and I'm at your service.",
      "Bague is the name you can refer to me by.",
      "I'm Bague, your friendly chatbot.",
      "You're chatting with Bague right now.",
      "I go by the name Bague, pleased to meet you.",
      "Call me Bague, your digital companion.",
      "I'm Bague, your virtual assistant.",
      "You can address me as Bague, how can I assist you?",
      "I'm Bague, here to help with your inquiries.",
      "Bague is the name, and assistance is my game.",
      "My name is Bague, ready to assist with your questions.",
      "You're talking to Bague, your chat companion.",
      "I'm known as Bague, your chatbot friend.",
      "Call me Bague, your virtual helper.",
      "I go by Bague, your digital buddy.",
      "I'm Bague, here to provide information and assistance.",
      "Bague is the name, how can I assist you today?",
    ],
    option: ["Getting started", "About bague"],
  },
  {
    id: 18,
    keyword: [
      "Tell me about yourself",
      "Who are you?",
      "Introduce yourself",
      "About the chatbot",
      "Your background",
      "Chatbot information",
      "Your identity",
      "Your purpose",
      "What can you do?",
      "Chatbot details",
      "About you",
      "Self-description",
      "Background of the chatbot",
      "What are you?",
      "Your characteristics",
      "Tell me about your capabilities",
      "Chatbot profile",
      "Who is Bague?",
      "Information about Bague",
      "Bague's description",
      "Chatbot's features",
      "What do you do?",
      "Your functions",
      "Bague's background",
      "Chatbot introduction",
      "What is your purpose?",
      "Chatbot's role",
      "Tell me about your features",
      "About your functionality",
      "Describe yourself",
      "Your chatbot abilities",
      "Your chatbot functions",
      "Information about you",
      "Your chatbot traits",
      "Your chatbot's mission",
      "What can you tell me about yourself?",
      "Elaborate on your capabilities",
      "Your chatbot's identity",
      "Your chatbot's qualities",
      "Explain your purpose",
      "About the chatbot Bague",
      "Bague's functions",
      "Bague's abilities",
      "Bague's characteristics",
      "Who is Bague, the chatbot?",
    ],
    response: [
      "I'm just a chatbot here to assist you with information about this site.",
      "My primary role is to help users like you by answering questions related to this website.",
      "I exist to provide information and assist users with inquiries about this site.",
      "Think of me as your digital assistant, dedicated to helping you navigate this website.",
      "I'm here to make your experience on this site as smooth as possible by providing information and guidance.",
      "I'm a chatbot created to offer support and information regarding this website's features and services.",
      "I'm at your service, ready to answer any questions you may have about this site.",
      "My purpose is to assist users like you in getting the most out of this website.",
      "You can consider me as your virtual helper, available to provide information about this site.",
      "I'm just a chatbot, but I'm here to assist you with any inquiries you have about this website.",
      "I'm designed to provide information and help users find what they need on this site.",
      "I'm here to make your interaction with this website more convenient and informative.",
      "My goal is to assist and guide you through this site's features and functionalities.",
      "I'm your friendly chatbot, and I'm here to assist you with any questions you may have about this website.",
      "Feel free to ask me anything about this site, and I'll do my best to provide you with the information you need.",
      "I'm here to provide support and information to enhance your experience on this website.",
      "You can count on me to help you find answers to your questions about this site.",
      "I'm dedicated to assisting users like you with their inquiries related to this website.",
      "My role is to assist and guide you through the various aspects of this website.",
      "I'm your digital companion here to help you with this site's features and functionalities.",
    ],
    option: ["About developer", "Send money"],
  },
];

export const services = [
  "Please send an email to soolaimangee@gmail.com with your details (email, account number, and transaction ID if required).",
  "You can reach out to us via email at soolaimangee@gmail.com, providing your email address, account number, and transaction ID if needed.",
  "For assistance, kindly send an email to soolaimangee@gmail.com and include your email, account number, and transaction ID (if applicable).",
  "Feel free to contact us by sending an email to soolaimangee@gmail.com. Remember to include your email, account number, and transaction ID if necessary.",
  "To get help, please email us at soolaimangee@gmail.com and include your email address, account number, and transaction ID if it's related to your inquiry.",
  "For further assistance, send an email to soolaimangee@gmail.com, and be sure to include your email, account number, and transaction ID if it applies.",
  "You can get in touch with us via email at soolaimangee@gmail.com. Ensure you provide your email, account number, and transaction ID (if relevant) in your message.",
  "To reach our support team, send an email to soolaimangee@gmail.com with your email, account number, and transaction ID (if required) included.",
  "Please send an email to soolaimangee@gmail.com with the necessary details: your email, account number, and transaction ID if it's relevant to your query.",
  "If you need assistance, don't hesitate to email us at soolaimangee@gmail.com. Make sure to include your email address, account number, and transaction ID (if applicable).",
];
