import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import type { Metadata } from "next";
import ChatBot from "@/components/Bot/chatBot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` dark:bg-blacks-500 dark:text-gray-200`}>
        {children}
        <Toaster />
        <ChatBot />
      </body>
    </html>
  );
}
