import { useEffect, useState } from "react";

/**
 * UseCheck -->A Custom hook to check the strength of password, if email is valid and username length
 * @param value -->What the user wants to check should be a string
 * @param type  -->The type this is the type of what the user wants to check either password | email | username
 * @returns
 */

export const useCheck = (
  value: string,
  type: "email" | "password" | "username"
) => {
  //Email, Password and Username Regex generated by ChatGPT -->https://open.ai/chat
  const passwordRegex = /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d).{8,}$/;
  const emailRegex =
    /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
  const usernameRegex = /^[a-zA-Z]+$/;

  let [res, setRes] = useState(false); //If the value meets the user requirement turns to true else remains false

  /**
   * UseEffect to keeps checking the input that is the value pass in
   */
  useEffect(() => {
    switch (type) {
      case "email":
        setRes(emailRegex.test(value));
        break;
      case "password":
        setRes(passwordRegex.test(value));
        break;
      case "username":
        setRes(usernameRegex.test(value));
        break;
      default:
        break;
    }
  }, [value]);

  return res; //Retrun TRUE or FALSE
};
